//! Protocol-specific configuration for the PROFIBUS-DP connector.
//!
//! Three opaque config slots filled by this module:
//! * `[connection]`              → [`BusConnection`]   (port, baudrate, master address)
//! * `device.protocol_address`  → [`PeripheralAddress`] (station address, I/O byte counts, …)
//! * `point.address`            → [`PointAddress`]     (byte offset, optional bit offset)

use serde::Deserialize;

// ── connection ───────────────────────────────────────────────────────────────

/// `[connection]` block: parameters shared across all PROFIBUS peripherals on this bus.
#[derive(Debug, Clone, Deserialize)]
pub struct BusConnection {
    /// Bus transport: a serial port device (e.g. `/dev/ttyUSB0`, `/dev/ttyS0`)
    /// or `tcp://host:port` for a serial-over-TCP byte stream (RS-485 ⇄ TCP
    /// device servers, or the containerised slave simulator).
    pub port: String,
    /// Bus baudrate in bits/second. Must be one of the PROFIBUS standard rates.
    /// Supported: 9600, 19200, 93750, 187500, 500000, 1500000, 3000000, 6000000, 12000000.
    #[serde(default = "default_baudrate")]
    pub baudrate: u32,
    /// FDL station address of *this* master (0–126). Defaults to 2.
    #[serde(default = "default_master_address")]
    pub master_address: u8,
    /// FDL slot-bit count, a timing parameter from the GSD file or bus design.
    /// Typical value: 300 at 19200 bps.
    #[serde(default = "default_slot_bits")]
    pub slot_bits: u16,
}

impl Default for BusConnection {
    fn default() -> Self {
        BusConnection {
            port: "/dev/ttyUSB0".to_string(),
            baudrate: default_baudrate(),
            master_address: default_master_address(),
            slot_bits: default_slot_bits(),
        }
    }
}

impl BusConnection {
    /// Map the numeric baudrate to the `profirust::Baudrate` enum.
    pub fn profirust_baudrate(&self) -> profirust::Baudrate {
        use profirust::Baudrate;
        match self.baudrate {
            9_600 => Baudrate::B9600,
            19_200 => Baudrate::B19200,
            93_750 => Baudrate::B93750,
            187_500 => Baudrate::B187500,
            500_000 => Baudrate::B500000,
            1_500_000 => Baudrate::B1500000,
            3_000_000 => Baudrate::B3000000,
            6_000_000 => Baudrate::B6000000,
            12_000_000 => Baudrate::B12000000,
            other => {
                tracing::warn!("unsupported baudrate {other}, defaulting to 19200");
                Baudrate::B19200
            }
        }
    }
}

fn default_baudrate() -> u32 {
    19_200
}
fn default_master_address() -> u8 {
    2
}
fn default_slot_bits() -> u16 {
    300
}

// ── peripheral (device) address ──────────────────────────────────────────────

/// `device.protocol_address`: how to reach and configure a PROFIBUS DP slave.
///
/// The `ident_number`, `config_bytes`, `param_bytes`, and I/O sizes are all found
/// in the peripheral's GSD file.  The [`gsdtool`](https://github.com/Rahix/profirust)
/// utility generates the exact Rust literals; copy the relevant values here.
#[derive(Debug, Clone, Deserialize)]
pub struct PeripheralAddress {
    /// PROFIBUS station address of the peripheral (1–125).
    pub station_address: u8,
    /// Peripheral identification number from its GSD file.
    #[serde(default)]
    pub ident_number: u16,
    /// Maximum station delay response time (Tsdr) from the GSD file.
    /// Typically a few hundred bit-times; 0 = profirust default.
    #[serde(default)]
    pub max_tsdr: u16,
    /// Module configuration bytes generated by `gsdtool` (`Chk_Cfg` payload).
    /// Specifies which I/O modules are active and their type/size.
    #[serde(default)]
    pub config_bytes: Vec<u8>,
    /// User parameter bytes generated by `gsdtool` (`Set_Prm` UserPrm payload).
    /// Leave empty if the peripheral uses default parameters.
    #[serde(default)]
    pub param_bytes: Vec<u8>,
    /// Total number of **input** bytes (PI_I buffer size) for this peripheral.
    /// Must match the I/O sizes implied by `config_bytes`.
    pub input_bytes: usize,
    /// Total number of **output** bytes (PI_Q buffer size) for this peripheral.
    /// Must match the I/O sizes implied by `config_bytes`.
    pub output_bytes: usize,
}

// ── point address ─────────────────────────────────────────────────────────────

/// Direction of a data point relative to the master.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Direction {
    /// Input from the peripheral (PI_I buffer — sensor / measurement data).
    Input,
    /// Output to the peripheral (PI_Q buffer — actuator / control data).
    Output,
}

/// `point.address`: location of a data point within a peripheral's I/O buffer.
#[derive(Debug, Clone, Deserialize)]
pub struct PointAddress {
    /// Whether this is an input (PI_I) or output (PI_Q) point.
    pub direction: Direction,
    /// Zero-based byte offset within the I/O buffer.
    pub byte_offset: usize,
    /// Zero-based bit offset within the byte at `byte_offset` (0–7).
    /// Present only for single-bit boolean points.
    #[serde(default)]
    pub bit_offset: Option<u32>,
    /// Number of bits to extract when `bit_offset` is set.
    /// Defaults to 1 for boolean points.
    #[serde(default)]
    pub bit_count: Option<u32>,
}

impl PointAddress {
    /// Returns `true` if this is a bus input (readable) direction.
    pub fn is_input(&self) -> bool {
        self.direction == Direction::Input
    }

    /// Number of whole bytes this point occupies (derived from the declared datatype at
    /// configure time, but used here for validation).
    pub fn byte_count(&self, datatype_bytes: usize) -> usize {
        if self.bit_offset.is_some() {
            1
        } else {
            datatype_bytes
        }
    }
}

// ── defaults ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_bus_connection_defaults() {
        let v = serde_json::json!({ "port": "/dev/ttyUSB0" });
        let c: BusConnection = serde_json::from_value(v).unwrap();
        assert_eq!(c.port, "/dev/ttyUSB0");
        assert_eq!(c.baudrate, 19_200);
        assert_eq!(c.master_address, 2);
        assert_eq!(c.slot_bits, 300);
    }

    #[test]
    fn parse_bus_connection_explicit() {
        let v = serde_json::json!({
            "port": "/dev/ttyS0", "baudrate": 93750,
            "master_address": 5, "slot_bits": 400
        });
        let c: BusConnection = serde_json::from_value(v).unwrap();
        assert_eq!(c.baudrate, 93_750);
        assert_eq!(c.master_address, 5);
        assert!(matches!(c.profirust_baudrate(), profirust::Baudrate::B93750));
    }

    #[test]
    fn parse_peripheral_address() {
        let v = serde_json::json!({
            "station_address": 7,
            "ident_number": 1234,
            "max_tsdr": 150,
            "config_bytes": [1, 2, 3],
            "param_bytes": [0xAB, 0xCD],
            "input_bytes": 4,
            "output_bytes": 2
        });
        let a: PeripheralAddress = serde_json::from_value(v).unwrap();
        assert_eq!(a.station_address, 7);
        assert_eq!(a.ident_number, 1234);
        assert_eq!(a.input_bytes, 4);
        assert_eq!(a.output_bytes, 2);
        assert_eq!(a.config_bytes, vec![1, 2, 3]);
    }

    #[test]
    fn parse_peripheral_address_minimal() {
        let v = serde_json::json!({
            "station_address": 3,
            "input_bytes": 8,
            "output_bytes": 0
        });
        let a: PeripheralAddress = serde_json::from_value(v).unwrap();
        assert_eq!(a.station_address, 3);
        assert!(a.config_bytes.is_empty());
        assert!(a.param_bytes.is_empty());
        assert_eq!(a.ident_number, 0);
    }

    #[test]
    fn parse_point_address_byte() {
        let v = serde_json::json!({
            "direction": "input", "byte_offset": 2
        });
        let a: PointAddress = serde_json::from_value(v).unwrap();
        assert!(a.is_input());
        assert_eq!(a.byte_offset, 2);
        assert!(a.bit_offset.is_none());
    }

    #[test]
    fn parse_point_address_bit() {
        let v = serde_json::json!({
            "direction": "input", "byte_offset": 0,
            "bit_offset": 3, "bit_count": 1
        });
        let a: PointAddress = serde_json::from_value(v).unwrap();
        assert_eq!(a.bit_offset, Some(3));
        assert_eq!(a.bit_count, Some(1));
    }

    #[test]
    fn parse_point_address_output() {
        let v = serde_json::json!({ "direction": "output", "byte_offset": 0 });
        let a: PointAddress = serde_json::from_value(v).unwrap();
        assert!(!a.is_input());
    }

    #[test]
    fn baudrate_mapping_exhaustive() {
        for (baud, variant) in [
            (9_600u32, profirust::Baudrate::B9600),
            (19_200, profirust::Baudrate::B19200),
            (93_750, profirust::Baudrate::B93750),
            (187_500, profirust::Baudrate::B187500),
            (500_000, profirust::Baudrate::B500000),
            (1_500_000, profirust::Baudrate::B1500000),
            (3_000_000, profirust::Baudrate::B3000000),
            (6_000_000, profirust::Baudrate::B6000000),
            (12_000_000, profirust::Baudrate::B12000000),
        ] {
            let c = BusConnection {
                baudrate: baud,
                ..Default::default()
            };
            // Just verify it maps to the right variant (PartialEq on Baudrate)
            assert_eq!(
                std::mem::discriminant(&c.profirust_baudrate()),
                std::mem::discriminant(&variant),
                "baudrate {baud} mapped to wrong variant"
            );
        }
    }
}
